### ISSUE TITLE
Directions

### ISSUE THREAD

**Issue by outrunthewolf** [Here-Be-Dragons/familamp#1]
For those who only have some experience with hardware, is this project do-able with off the shelf components? And if not, what would you advise?

This is great by the way. Do you have plans to build them as purchasable units?

**Comment by Here-Be-Dragons** [comment]
I do not have plans to make purchasable units, but there are a couple other similar projects for sale around the internet.  The most time intensive part is the fabrication of the light box and top.  The electronics bit can be done with off-the-shelf components, and if you did not want to order PCBs they could be done with perfboard.  I find perfboard difficult to use, which is why I went the PCB route.
