### ISSUE TITLE
C Variable not globally declared

### ISSUE THREAD

**Issue by davidginn524** [Here-Be-Dragons/familamp#7]
Hello 
It has been noticed that         c = random(0,255); is not globally declared anywhere. You have it in multiple functions. I couldn't tell if this was intentional. 
Let me know your thoughts

**Comment by Here-Be-Dragons** [comment]
I use single-letter variables mostly for throw-away variables that will become undefined once you leave the function.  This is usually when I am storing intermediate values or values that are not useful outside of the given function.   As far as `c` goes, because I store the current color in `activeColor` which is globally declared, it didn't seem like `c` should be global.  There is probably a better way to handle this, but it was a style used in the early code that I kept as things progressed.

Does this answer your question?

**Comment by davidginn524** [comment]
Ahh yes that makes total sense now. ignore me then! I can't program :)
